server:
  port: 9003
spring:
  application:
    name: dispatcher-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
    function:
      definition: pack|label # 스프링 클라우드 함수가 관리할 함수 정의 -> rabbitMq의 입출력 바인딩의 이름으로 사용(packlabel-in,out-0)
    stream:
      bindings:
        packlabel-in-0: # 입력 바인딩(연결 통로 역할)
          destination: order-accepted # rabbitMq의 익스체이지(바인더를 연결할 대상의 브로커 내에서의 실제 이름)
          group: ${spring.application.name} # 대상에 관심을 갖는 소비자 그룹
        packlabel-out-0: # 아웃 바인딩 역할
          destination: order-dispatched # rabbitMq의 익스체이지(바인더를 연결할 대상의 브로커 내에서의 실제 이름)
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: bindings, configprops, env, functions, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}